name: Test Only

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Run Unit and Integration Tests
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libinsighttoolkit5-dev libgtest-dev cmake build-essential

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

    - name: Build project
      run: |
        cd build
        make -j$(nproc)

    - name: Run all tests
      run: |
        chmod +x tests/run_tests.sh
        ./tests/run_tests.sh -m all